import os

TELEGRAM_BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHANNEL_ID = os.environ.get("TELEGRAM_CHANNEL_ID", "")
TELEGRAM_USER_ID = os.environ.get("TELEGRAM_USER_ID", "")
OPENWEATHER_API_KEY = os.environ["OPENWEATHER_API_KEY"]
GROQ_API_KEY = os.environ["GROQ_API_KEY"]

SPOTIFY_CLIENT_ID = os.environ.get("SPOTIFY_CLIENT_ID", "")
SPOTIFY_CLIENT_SECRET = os.environ.get("SPOTIFY_CLIENT_SECRET", "")

SPORTRADAR_SOCCER_API_KEY = os.environ.get("SPORTRADAR_SOCCER_API_KEY", "")
SPORTRADAR_BASKETBALL_API_KEY = os.environ.get("SPORTRADAR_BASKETBALL_API_KEY", "")
SPORTRADAR_VOLLEYBALL_API_KEY = os.environ.get("SPORTRADAR_VOLLEYBALL_API_KEY", "")

MASHHAD_LAT = 36.2605
MASHHAD_LON = 59.6168

GROQ_MODEL = "openai/gpt-oss-120b"
GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"
